name: Build

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

jobs:
  # We are going to build an image specifically for final deployment and push it to ghcr.io (GitHub Container Registry)
  build-final-image:
    name: Build Image for Deployment (Production)
    runs-on: ubuntu-latest

    permissions:
      packages: write # Needed to push docker image to ghcr.io
      contents: read # Needed to read code in repository

    steps:
      # Docker buildx is useful for caching images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:production
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:production
          cache-to: type=inline # Inline cache is stored in the registry, embedded into the main image, and is pulled alongside the main image.
          target: final # This is the target stage in the Dockerfile
          labels: |
            org.opencontainers.image.title=Production Image
            org.opencontainers.image.description=Image used for production
            org.opencontainers.image.source=ghcr.io/${{ github.repository }}

  clean-old-images:
    name: Clean Old Images
    runs-on: self-hosted
    needs: [build-final-image]

    permissions:
      packages: write

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: true
